# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-22 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('urltoimage', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('business', 'business'), ('entertainment', 'entertainment'), ('general', 'general'), ('health', 'health'), ('science', 'science'), ('sports', 'sports'), ('technology', 'technology'), ('more', 'more')], max_length=200)),
                ('country', models.CharField(choices=[('ae', 'ae'), ('ar', 'ar'), ('at', 'at'), ('au', 'au'), ('be', 'be'), ('bg', 'bg'), ('br', 'br'), ('ca', 'ca'), ('ch', 'ch'), ('cn', 'cn'), ('co', 'co'), ('cu', 'cu'), ('cz', 'cz'), ('de', 'de'), ('eg', 'eg'), ('fr', 'fr'), ('gb', 'gb'), ('gr', 'gr'), ('hk', 'hk'), ('hu', 'hu'), ('id', 'id'), ('ie', 'ie'), ('il', 'il'), ('in', 'in'), ('it', 'it'), ('jp', 'jp'), ('kr', 'kr'), ('lt', 'lt'), ('lv', 'lv'), ('ma', 'ma'), ('mx', 'mx'), ('my', 'my'), ('ng', 'ng'), ('nl', 'nl'), ('no', 'no'), ('nz', 'nz'), ('ph', 'ph'), ('pl', 'pl'), ('pt', 'pt'), ('ro', 'ro'), ('rs', 'rs'), ('ru', 'ru'), ('sa', 'sa'), ('se', 'se'), ('sg', 'sg'), ('si', 'si'), ('sk', 'sk'), ('th', 'th'), ('tr', 'tr'), ('tw', 'tw'), ('ua', 'ua'), ('us', 'us'), ('ve', 've'), ('za', 'za')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('uid', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(null=True)),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('business', 'business'), ('entertainment', 'entertainment'), ('general', 'general'), ('health', 'health'), ('science', 'science'), ('sports', 'sports'), ('technology', 'technology'), ('more', 'more')], max_length=200)),
                ('language', models.CharField(choices=[('ar', 'ar'), ('de', 'de'), ('en', 'en'), ('es', 'es'), ('fr', 'fr'), ('he', 'he'), ('it', 'it'), ('nl', 'nl'), ('no', 'no'), ('pt', 'pt'), ('ru', 'ru'), ('se', 'se'), ('ud', 'ud'), ('zh', 'zh'), ('es', 'es'), ('fr', 'fr'), ('he', 'he'), ('it', 'it'), ('nl', 'nl'), ('no', 'no'), ('pt', 'pt'), ('ru', 'ru'), ('se', 'se'), ('ud', 'ud'), ('zh', 'zh')], max_length=200)),
                ('country', models.CharField(choices=[('ae', 'ae'), ('ar', 'ar'), ('at', 'at'), ('au', 'au'), ('be', 'be'), ('bg', 'bg'), ('br', 'br'), ('ca', 'ca'), ('ch', 'ch'), ('cn', 'cn'), ('co', 'co'), ('cu', 'cu'), ('cz', 'cz'), ('de', 'de'), ('eg', 'eg'), ('fr', 'fr'), ('gb', 'gb'), ('gr', 'gr'), ('hk', 'hk'), ('hu', 'hu'), ('id', 'id'), ('ie', 'ie'), ('il', 'il'), ('in', 'in'), ('it', 'it'), ('jp', 'jp'), ('kr', 'kr'), ('lt', 'lt'), ('lv', 'lv'), ('ma', 'ma'), ('mx', 'mx'), ('my', 'my'), ('ng', 'ng'), ('nl', 'nl'), ('no', 'no'), ('nz', 'nz'), ('ph', 'ph'), ('pl', 'pl'), ('pt', 'pt'), ('ro', 'ro'), ('rs', 'rs'), ('ru', 'ru'), ('sa', 'sa'), ('se', 'se'), ('sg', 'sg'), ('si', 'si'), ('sk', 'sk'), ('th', 'th'), ('tr', 'tr'), ('tw', 'tw'), ('ua', 'ua'), ('us', 'us'), ('ve', 've'), ('za', 'za')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_source', to='core.Source'),
        ),
    ]
